# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- powershell: |
    Install-Module PSScriptAnalyzer -Scope Currentuser -SkipPublisherCheck
    Invoke-Pester -Path ./Tests -OutputFormat NUnitXml -OutputFile TestResults.xml -PassThru
  displayName: 'Pester'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'NUnit'
    testResultsFiles: '**/Test*.xml'

- powershell: |
    $Module = find-module psgitchangelog

    [version]$Version = $Module.Version

    $NewVersion = "{0}.{1}.{2}" -f $version.Major,$version.Minor,($version.Build + 1)

    Write-Host New SemVer is: $NewVersion
  displayName: New Semver