# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- powershell: |
    Install-Module PSScriptAnalyzer -Scope Currentuser -SkipPublisherCheck
    $TestResults = Invoke-Pester -Path ./Tests -OutputFormat NUnitXml -OutputFile TestResults.xml -PassThru
    
    if ($TestResults.FailedCount -gt 0) {
        Throw "Failed '$($TestResults.FailedCount)' tests, build failed"
        Exit
    }

  displayName: 'Pester'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'NUnit'
    testResultsFiles: '**/Test*.xml'

- powershell: |
    $Module = find-module psgitchangelog

    [version]$Version = $Module.Version

    $NewVersion = "{0}.{1}.{2}" -f $version.Major,$version.Minor,($version.Build + 1)

    Write-Host New SemVer is: $NewVersion
    Write-Host "##vso[task.setvariable variable=Build.SemVerId;]$NewVersion"
  displayName: New Semver 
- task: PowerShell@2
  inputs:
    filePath: 'Publish-ToPSGallery'
    arguments: '-nuGetApiKey $(PSGallery_PAT) -moduleVersion $(Build.SemVerId)'
